services:
  frontend:
    build: ./frontend
    ports:
      - 3000:3000
    container_name: oculus-frontend
    restart: always

  backend:
    build: ./backend
    ports:
      - 4500:4500
    container_name: oculus-backend
    restart: always
